### ISSUE TITLE
What's the diff between 'tagin! SDK' and this repo?

### ISSUE THREAD

**Issue by imknown** [misakuo/3dTagCloudAndroid#12]
https://sites.google.com/site/tagindemo/TagCloud
I failed in tagindemo 2 years ago...

**Comment by misakuo** [comment]
In fact they are almost completely different in addition to the trigonometric algorithm, but this repo was very inspired by tagindemo.
The contributors and me was making a lot of engineering improvements, makes it more robust and easy to use, but the tagindemo, looks more like a… toy, you know.
Just try it 😄

**Comment by imknown** [comment]
Thanks~ I will.
