### ISSUE TITLE
White tag text color is shown black

### ISSUE THREAD

**Issue by breaxta** [misakuo/3dTagCloudAndroid#4]
It is not possible to set white as dark or light tag text color.

When I set #ffffff as darkColor or lightColor the text color of the tag cloud is always shown black.

Also when I set a grey color tone e.g. #63696b the result is a yellow tone.

**Comment by misakuo** [comment]
Hi, this problem was resolved, you can import [the newest lib](https://bintray.com/misakuo/maven/tagcloudview/1.1.0/view) to your project now.

**Comment by breaxta** [comment]
Perfect! Thank you very much, awesome library!
