### ISSUE TITLE
标签设置点击事件和手势滑动球体事件冲突

### ISSUE THREAD

**Issue by liukkevin** [misakuo/3dTagCloudAndroid#5]
标签设置点击事件和手势滑动球体事件冲突，可以解决并加上此功能吗。不胜感谢。

**Comment by misakuo** [comment]
Fixed here https://github.com/misakuo/3dTagCloudAndroid/commit/fc4fc0495a685052a2af719f980d503570c1d035

**Comment by misakuo** [comment]
修复了，对触摸事件处理也做了一些优化，稍后会更新maven仓库内的版本到1.1.1，谢谢您的反馈；）

**Comment by liukkevin** [comment]
非常感谢！
